## MLP - XOR & AND
Change the expected output according to the logical function

In [1]:
import numpy as np
import math

In [2]:
#Input and corresponding output
inputs = np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])   # with bias
expected_output = np.array([[0],[1],[1],[0]])

In [3]:
#Input neurons, hidden neurons, output neurons
inp_neurons = 2
hidden_neurons = 2
output_neurons = 1

In [4]:
weight_matrix1 = np.random.uniform(size=(hidden_neurons,inp_neurons+1))   # 2*3 matrix
weight_matrix2 = np.random.uniform(size=(output_neurons,hidden_neurons+1))   # 1*3 matrix
print(weight_matrix1, weight_matrix2)

[[0.78773181 0.23284633 0.18604102]
 [0.58843871 0.10108829 0.4515005 ]] [[0.03656122 0.17215174 0.94060223]]


In [5]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [6]:
def sigmoid_derivative(x):
    return x * (1 - x)

###  Try changing the epochs and learning rate to get better results

In [7]:
#Training

epoch = 15000
learning_rate = 0.1


for i in range(0,epoch):
    #Forward Propagation
    hidden_layer_activation = []
    output_layer_activation = []
    for j in range(0,len(inputs)):
        temp = np.dot(weight_matrix1,inputs[j])
        temp = sigmoid(temp)
        hidden_layer_activation.append(temp)
    hidden_layer_activation = np.array(hidden_layer_activation)
    hidden_layer_output = np.insert(hidden_layer_activation, 0, values=1, axis=1)
#     print('HIDDEN LAYER OUTPUT:', hidden_layer_output)
    
    for j in range(0,len(hidden_layer_output)):
        temp = np.dot(weight_matrix2,hidden_layer_output[j])
        output_layer_activation.append(temp)
    output_layer_activation = np.array(output_layer_activation)
    predicted_output = sigmoid(output_layer_activation)
#     print('PREDICTED OUTPUT:', predicted_output)
    
    
    #Error calculation
    oplayer_error = expected_output - predicted_output 
    derivative_oplayer_error = oplayer_error * sigmoid_derivative(predicted_output)
#     print('OUTPUT ERROR:', oplayer_error)
#     print('DERIVATIVE OUTPUT ERROR:', derivative_oplayer_error)
    
    hl1_error = np.dot(derivative_oplayer_error,weight_matrix2) 
    derivative_hl1_error = hl1_error * sigmoid_derivative(hidden_layer_output)
    derivative_hl1_error = np.delete(derivative_hl1_error,0,1)
#     print('HL1 ERROR:', hl1_error)
#     print('DERIVATIVE HL1 ERROR:',derivative_hl1_error)
    
    #Update weight
    weight_matrix2 += derivative_oplayer_error.T.dot(hidden_layer_output) * learning_rate
    weight_matrix1 += derivative_hl1_error.T.dot(inputs)*learning_rate
#     print('WEIGHT MATRIX 2: ',weight_matrix2)
#     print('WEIGHT MATRIX 1: ',weight_matrix1)
    
print(predicted_output)
    

[[0.04267466]
 [0.96168588]
 [0.96171207]
 [0.04075645]]


In [8]:
print('FINAL INPUT LAYER WEIGHTS:\n', weight_matrix1)    # with bias
print('FINAL HIDDEN LAYER WEIGHTS:\n', weight_matrix2)   # with bias
print('PREDICTED OUTPUT:\n', predicted_output)

FINAL INPUT LAYER WEIGHTS:
 [[-6.0381573   3.93855382  3.93624542]
 [-2.58705417  6.0514482   6.04022676]]
FINAL HIDDEN LAYER WEIGHTS:
 [[-3.65536192 -8.7958442   8.08423556]]
PREDICTED OUTPUT:
 [[0.04267466]
 [0.96168588]
 [0.96171207]
 [0.04075645]]


In [9]:
#Calculating Accuracy 
final_error = expected_output - predicted_output
final_error = np.sum(final_error)
final_error = abs(final_error)
print('TOTAL ERROR:', final_error)
print('ACCURACY: {}%'.format((1-final_error)*100))

TOTAL ERROR: 0.006829064381882202
ACCURACY: 99.31709356181177%
