In [1]:
import numpy as np
import pandas as pd
import math
import random 

### Set output for each logical function before using 
The first entry in inp is for bias. We take bias value to be 1

In [2]:
inp = [[1,0,0], [1,0,1], [1,1,0], [1,1,1]]
outp = [0,0,0,1]
inp = np.array(inp).reshape(4,3)
outp = np.array(outp).reshape(4,1)
learning_rate = 0.1

In [3]:
print('INPUT: ',inp)
print('OUTPUT: ',outp)
print('LEARNING RATE: ',learning_rate)
rows = 4
cols = 3

INPUT:  [[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
OUTPUT:  [[0]
 [0]
 [0]
 [1]]
LEARNING RATE:  0.1


In [4]:
#Initialise random weights
weights = np.random.uniform(low=-0.9, high=0.9, size=(3,))
np.transpose(weights)
print(weights)

[-0.74743402  0.71893076 -0.78208045]


In [5]:
# Forward propagation with a weight
# then find error
# if error = 0 stop that is the cost
# else do backpropagation 

# In Feedforward, calculate the sum of weights and input
# weights is 1*3
# input is 4*3
# thus take weights transpose
# sum = input * weight(T) 

def feedForward(input_values):
    sum_value = (np.dot(input_values,weights))
    if sum_value > 0:
        sum_value = 1
    else:
        sum_value = 0
    return sum_value

In [6]:
def costFunction(predicted_output, actual_output):
    error = 0
    for i in range(0,len(predicted_output)):
        error = error + abs(predicted_outp - actual_output[i])

In [7]:
def backPropagate(weights, predicted_output, actual_output, inp):
    for i in range(0,len(weights)):
        weights[i] = weights[i] + learning_rate * (actual_output - predicted_output) * inp[i]
    return weights

In [8]:
# Set epoch to 45000 for XOR function
epoch = 1000
for j in range(0,epoch):
    error = 0
    for i in range(0,len(inp)):
        predicted_output = feedForward(inp[i])
        if predicted_output != outp[i]:
            weights = backPropagate(weights, predicted_output, outp[i], inp[i])
            error = error + 1
    print('ITERATION {}:'.format(j),weights,'\n')
    if error == 0:
        break

ITERATION 0: [-0.64743402  0.81893076 -0.68208045] 

ITERATION 1: [-0.64743402  0.81893076 -0.58208045] 

ITERATION 2: [-0.64743402  0.81893076 -0.48208045] 

ITERATION 3: [-0.64743402  0.81893076 -0.38208045] 

ITERATION 4: [-0.64743402  0.81893076 -0.28208045] 

ITERATION 5: [-0.64743402  0.81893076 -0.18208045] 

ITERATION 6: [-0.64743402  0.81893076 -0.08208045] 

ITERATION 7: [-0.64743402  0.81893076  0.01791955] 

ITERATION 8: [-0.64743402  0.81893076  0.11791955] 

ITERATION 9: [-0.74743402  0.71893076  0.11791955] 

ITERATION 10: [-0.74743402  0.71893076  0.11791955] 



In [9]:
if i>=epoch:
    print('Unable to linearly separate the logical function')
else :
    print('The function is linearly separable')
print('FINAL WEIGHTS: ', weights)

The function is linearly separable
FINAL WEIGHTS:  [-0.74743402  0.71893076  0.11791955]
